$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    responsive:{
        400:{
            items:1
        },
        700:{
            items:3
        },
        1000:{
            items:5
        }
    }
})